name: Publish
on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Setup repo
              uses: actions/checkout@v3

            - name: Setup Deno
              uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
              with:
                  deno-version: v2.x

            - name: Publish on tag
              run: deno run -A jsr:@david/publish-on-tag@0.1.4
