name: Test - QuickJS
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    Test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./quickjs

        permissions:
            contents: write
            id-token: write

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Run linter
              run: deno lint
              working-directory: ${{ env.working-directory }}

            - name: Run tests
              run: deno test --allow-read --allow-net
              working-directory: ${{ env.working-directory }}
